function createfigure_rer(X1, YMatrix1, var_name, shock_name, protocol)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  var_name: vector of strings
%  shock_name: string
%  protocol: string, one of {'pt', 'pb', 'nb'}

%  Auto-generated by MATLAB on 28-Sep-2010 10:31:03

% Create figure
figure1 = figure('XVisual','','Name',strcat('Shock to: ',shock_name));

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 30]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.0097744265952186 0.0171434822808811]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'Marker','o','Color',[0 0 1],'DisplayName',var_name(1,:));
set(plot1(2),'Marker','square','Color',[0 0.5 0],...
    'DisplayName',var_name(2,:));
set(plot1(3),'Marker','x','Color',[1 0 0],'DisplayName',var_name(3,:));
set(plot1(4),'Marker','.','Color',[0 0.75 0.75],'DisplayName',var_name(4,:));
set(plot1(5),'LineStyle','--','Color',[0 0 1],'DisplayName',shock_name);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',14,'FontAngle','italic');

% Save to EPS and FIG

filename = strcat('_figures/',protocol,'-',shock_name,'_rer');
print(gcf, '-depsc', filename) % EPS color
hgsave(filename) % FIG

