function [ VARNAMES ] = var_names_common()

    VARNAMES = 'X';                                              % 1
    VARNAMES = char(VARNAMES, 'X^{\ast}');                       % 2
    VARNAMES = char(VARNAMES, 'H');                              % 3
    VARNAMES = char(VARNAMES, 'H^{\ast}');                       % 4
    VARNAMES = char(VARNAMES, 'q');                              % 5
    VARNAMES = char(VARNAMES, 'q^{\ast}');                       % 6
    VARNAMES = char(VARNAMES, 'qz');                             % 7
    VARNAMES = char(VARNAMES, 'qz^{\ast}');                      % 8
    VARNAMES = char(VARNAMES, 'y_{h}');                          % 9
    VARNAMES = char(VARNAMES, 'y_{f}');                          % 10
    VARNAMES = char(VARNAMES, 'y_{f}^{\ast}');                   % 11
    VARNAMES = char(VARNAMES, 'y_{h}^{\ast}');                   % 12
    VARNAMES = char(VARNAMES, 'Nom. GDP');                       % 13
    VARNAMES = char(VARNAMES, 'Nom. GDP^{\ast}');                % 14
    VARNAMES = char(VARNAMES, 'e');                              % 15
    VARNAMES = char(VARNAMES, 'I');                              % 16
    VARNAMES = char(VARNAMES, 'I^{\ast}');                       % 17
    VARNAMES = char(VARNAMES, 'p');                              % 18
    VARNAMES = char(VARNAMES, 'p_{h}');                          % 19
    VARNAMES = char(VARNAMES, 'p_{h}^{\ast}');                   % 20
    VARNAMES = char(VARNAMES, 'p^{\ast}');                       % 21
    VARNAMES = char(VARNAMES, 'p_{f}^{\ast}');                   % 22
    VARNAMES = char(VARNAMES, 'p_{f}');                          % 23
    VARNAMES = char(VARNAMES, 'TOT_{CM}');                       % 24
    VARNAMES = char(VARNAMES, 'CON/CON^{\ast}');                 % 25
    VARNAMES = char(VARNAMES, 'NX');                             % 26
    VARNAMES = char(VARNAMES, 'NX^{\ast}');                      % 27
    VARNAMES = char(VARNAMES, 'TOT');                            % 28
    VARNAMES = char(VARNAMES, 'p_{DM,avg}');                     % 29
    VARNAMES = char(VARNAMES, 'p_{DM,avg}^{\ast}');              % 30
    VARNAMES = char(VARNAMES, 'P_{Y}');                          % 31
    VARNAMES = char(VARNAMES, 'P_{Y}^{\ast}');                   % 32
    VARNAMES = char(VARNAMES, 'RER');                            % 33 
    VARNAMES = char(VARNAMES, 'CON');                            % 34
    VARNAMES = char(VARNAMES, 'CON^{\ast}');                     % 35
    VARNAMES = char(VARNAMES, 'GDP');                            % 36
    VARNAMES = char(VARNAMES, 'GDP^{\ast}');                     % 37
    VARNAMES = char(VARNAMES, 'INV');                            % 38
    VARNAMES = char(VARNAMES, 'INV^{\ast}');                     % 39
    VARNAMES = char(VARNAMES, 'P_{Y}^{\ast}/P_{Y}');             % 40
    
    
    VARNAMES = char(VARNAMES, 'Home-K');                         % 41
    VARNAMES = char(VARNAMES, 'Foreign-K');                      % 42
    VARNAMES = char(VARNAMES, 'Home-TFP');                       % 43
    VARNAMES = char(VARNAMES, 'Foreign-TFP');                    % 44
    VARNAMES = char(VARNAMES, 'Home-Money');                     % 45
    VARNAMES = char(VARNAMES, 'Foreign-Money');                  % 46